### ISSUE TITLE
Connect outside local network

### ISSUE THREAD

**Issue by nicopsz** [danielchc/docker-acestream-x86_64#1]
Hi @danielchc! Thank you so much for the repo, it works like a charm!

I would want to connect to Acestream Docker outside local network opening the port 6878 in the router, but when I try to connect appears this log: `acestream.httpserver|deny access from IP`

I think the main cause is this parameter (allow_remote) in the initialization: `|MainThread|acestream.VideoServer|start: addr= port=6878 allow_remote=0 allow_intranet=1`

Do you know if this parameter can be activated through Dockerfile or similar?

Thank you so much, best regards.

**Comment by danielchc** [comment]
Hi,

You can add additional parameters in the file  `acestream.conf`. I've been searching for the parameter that allows the remote connection but I didn't find it.

I have done some research and I have seen that there are other people who have this problem, but they have [not found a solution either](https://github.com/magnetikonline/docker-acestream-server/issues/4).

Another option is use a reverse proxy to access to from outside. You can use `jwilder/nginx-proxy` for example.
